# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

############# SITE PROPERTIES #############

title: Pampa
tagline: Pampa|Open-source Planning Software
email: lwh@free.fr
description: > # this means to ignore newlines until "baseurl:"
  Planning software
domain : "lwh-21.github.io"
url: "https://lwh-21.github.io" # Site url, also used in jekyll-seo-tag
baseurl: "/Pampa"
repo: "https://github.com/LWH-21/Pampa/"
github_username:  LWH-21
encoding: UTF-8
author: LWH
logo: /assets/logos/logo.svg
locale: fr
language: french
format: web
favicons: # the little icon that appears in the browser window's tab
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'


############# EXCLUDE LIST #############
# these folders or files will not be included in the output. you can use wildcards with asterisks.
exclude:
  - Config
  - s3_website
  - _config_*
  - Gemfile*
  - serve_*
  - build_*
  - gem_*
  - pdf
  - mobi

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: Loewenguth Pascal

copyright:
   name: LWH
   link: 'http://lwh.free.fr'

# Build settings
markdown: kramdown
permalink: pretty
paginate: 6
paginate_path: /page:num/

############### SEO  ##################
# Tracker
analytics: 291347504

# Comments
disqus: no
disqus-shortname: 

#social
facebook: https://www.facebook.com/profile.php?id=100009215959255
quora: # http://quora.com/
twitter: Lwh18879714
github: https://github.com/LWH-21
email: lwh@free.fr

#facebook like box
fb-like-box: no
fb-app-id: 
fb-page-url: 
fb-page-title: 

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  


